const DEFAULT_MINIMUM_INDEXED_LENGTH = 3
const MINIMUM_INDEXED_LENGTH = process.env.MINIMUM_INDEXED_LENGTH ? process.env.MINIMUM_INDEXED_LENGTH : DEFAULT_MINIMUM_INDEXED_LENGTH

module.exports = {
  MINIMUM_INDEXED_LENGTH
}