const DEFAULT_MIN_INDEXED_LENGTH = 3;
const MIN_INDEXED_LENGTH = process.env.MIN_INDEXED_LENGTH
  ? process.env.MIN_INDEXED_LENGTH
  : DEFAULT_MIN_INDEXED_LENGTH;

module.exports = {
  MIN_INDEXED_LENGTH: MIN_INDEXED_LENGTH
};
